//! Progressive Web App (offline) support: generates a `service-worker.js`,
//! a `manifest.webmanifest`, and the HTML glue (manifest `<link>` +
//! registration `<script>`) needed to make an `appfront` app installable and

/// Configuration for the generated PWA assets.
#[derive(Debug, Clone)]
pub struct PwaConfig {
    /// Human-readable app name (used in the install prompt / launcher).
    pub name: String,
    /// Short name shown under the home-screen icon.
    pub short_name: String,
    /// One-line description (also reused for the manifest).
    pub description: String,
    /// Theme color (address bar / splash). Any CSS color is fine.
    pub theme_color: String,
    /// Background color for the splash screen.
    pub background_color: String,
    /// URL the PWA opens at (usually `/`).
    pub start_url: String,
    /// Cache storage name — bump to force a service-worker update.
    pub cache_name: String,
    /// Asset paths (relative to the origin) to precache on install, e.g.
    /// `"/"`, `"/app.wasm"`, `"/app.js"`.
    pub precache: Vec<String>,
}

impl Default for PwaConfig {
    fn default() -> Self {
        PwaConfig {
            name: "AppFront App".to_string(),
            short_name: "App".to_string(),
            description: String::new(),
            theme_color: "#3b82f6".to_string(),
            background_color: "#ffffff".to_string(),
            start_url: "/".to_string(),
            cache_name: "appfront-pwa-v1".to_string(),
            precache: vec!["/".to_string()],
        }
    }
}

/// Generates a `service-worker.js` (offline-first: precache on install,
/// serve cache-first, fall back to network and re-cache, then to the
/// start URL when both fail).
pub fn service_worker(cfg: &PwaConfig) -> String {
    let assets_literal = cfg
        .precache
        .iter()
        .map(|a| format!("{a:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    // Used as the final offline fallback when both cache and network miss.
    let fallback = cfg.start_url.clone();

    format!(
        r#"// Generated by appfront — offline-first service worker.
const CACHE = {cache:?};
const ASSETS = [{assets}];

self.addEventListener('install', (event) => {{
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
}});

self.addEventListener('fetch', (event) => {{
  const req = event.request;
  if (req.method !== 'GET') return;
  // Navigations are network-first so a redeploy isn't served stale from the
  // cache; only when the network is unreachable do we fall back to cached
  // content (cache_name still bounds asset staleness for non-navigation GETs).
  if (req.mode === 'navigate') {{
    event.respondWith(
      fetch(req).then((resp) => {{
        const copy = resp.clone();
        caches.open(CACHE).then((cache) => cache.put(req, copy));
        return resp;
      }}).catch(() => caches.match(req).then((c) => c || caches.match({fallback:?})))
    );
    return;
  }}
  event.respondWith(
    caches.match(req).then((cached) =>
      cached ||
      fetch(req).then((resp) => {{
        const copy = resp.clone();
        caches.open(CACHE).then((cache) => cache.put(req, copy));
        return resp;
      }}).catch(() => caches.match({fallback:?}))
    )
  );
}});
"#,
        cache = cfg.cache_name,
        assets = assets_literal,
        fallback = fallback,
    )
}

/// Generates a `manifest.webmanifest` (JSON).
pub fn manifest(cfg: &PwaConfig) -> String {
    let json = serde_json::json!({
        "name": cfg.name,
        "short_name": cfg.short_name,
        "description": cfg.description,
        "start_url": cfg.start_url,
        "display": "standalone",
        "background_color": cfg.background_color,
        "theme_color": cfg.theme_color,
        "icons": [],
    });
    serde_json::to_string_pretty(&json).unwrap_or_default()
}

/// `<link>` tag pointing at the web manifest. Embed once in `<head>`.
pub fn manifest_link() -> String {
    r#"<link rel="manifest" href="/manifest.webmanifest">"#.to_string()
}

/// `<script>` registering the service worker. Embed once in `<body>`;
/// registration is a no-op where `serviceWorker` is unavailable. `nonce` must
/// match the `Content-Security-Policy` `nonce` set on the document so the
/// inline script is allowed to run.
pub fn registration_script(nonce: &str) -> String {
    format!(
        r#"<script nonce="{nonce}">
if ('serviceWorker' in navigator) {{
  window.addEventListener('load', () => {{
    navigator.serviceWorker.register('/service-worker.js').catch((e) => console.error('SW registration failed', e));
  }});
}}
</script>"#,
        nonce = nonce,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> PwaConfig {
        PwaConfig {
            precache: vec!["/".to_string(), "/app.wasm".to_string()],
            ..Default::default()
        }
    }

    #[test]
    fn service_worker_precaches_assets_and_fallbacks() {
        let sw = service_worker(&cfg());
        assert!(sw.contains("const CACHE = \"appfront-pwa-v1\""));
        assert!(sw.contains("\"/\""));
        assert!(sw.contains("\"/app.wasm\""));
        assert!(sw.contains("cache.addAll(ASSETS)"));
        assert!(sw.contains("cache.put(req, copy)"));
        assert!(sw.contains("caches.match(\"/\")"));
    }

    #[test]
    fn manifest_is_valid_json_with_expected_fields() {
        let m = manifest(&cfg());
        let v: serde_json::Value = serde_json::from_str(&m).expect("manifest is JSON");
        assert_eq!(v["name"], "AppFront App");
        assert_eq!(v["display"], "standalone");
        assert_eq!(v["start_url"], "/");
        assert!(v["icons"].is_array());
    }

    #[test]
    fn glue_snippets_are_well_formed() {
        assert!(manifest_link().contains(r#"rel="manifest""#));
        assert!(manifest_link().contains("/manifest.webmanifest"));
        assert!(registration_script("test-nonce").contains("/service-worker.js"));
        assert!(registration_script("test-nonce").contains("serviceWorker"));
        assert!(registration_script("test-nonce").contains("nonce=\"test-nonce\""));
    }
}
